name: release

on:
  push:
    branches:
      - 'main'
      - 'next'

jobs:
  kubernetes-version-tests:
    environment: gcloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minor:
          - '17'
          - '18'
          - '19'
          - '20'
        dbmode:
          - 'dbless'
          - 'postgres'
    steps:
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: cache go modules
        uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-codegen-

      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: test ${{ matrix.dbmode }} on GKE v1.${{ matrix.minor }}
        run: ./hack/e2e/run.sh
        env:
          KUBERNETES_MAJOR_VERSION: 1
          KUBERNETES_MINOR_VERSION: ${{ matrix.minor }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          GOOGLE_LOCATION: ${{ secrets.GOOGLE_LOCATION }}

  # TODO: kubernetes latest job (test against v1.20.7 and v1.21.2) FIXME: find out how to tolerate task failure
  # TODO: right now the release is not fully automated, but the above tests must pass before a release is made manually. See RELEASE.md for more information.
  # TODO: needs a cleanup job or cron to clean up any clusters that failed to clean properly
